# Generated by Django 3.2.3 on 2021-05-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_id', models.IntegerField()),
                ('record_id', models.IntegerField()),
                ('match_type', models.CharField(choices=[('1', 'Strong Match'), ('2', 'Possible Match'), ('3', 'Weak Match')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('alt_first_name', models.CharField(blank=True, max_length=100)),
                ('alt_last_name', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
